#!/bin/bash

for ((num=1; num < 101; num++)); do
curl 'http://1d3p.wp.codeforces.com/new' \
  -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9' \
  -H 'Accept-Language: ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -H 'Cookie: __utmc=71512449; evercookie_cache=gokmx699hkhzdgyqh7; evercookie_etag=gokmx699hkhzdgyqh7; evercookie_png=gokmx699hkhzdgyqh7; 70a7c28f3de=gokmx699hkhzdgyqh7; __utmz=71512449.1663870704.5.3.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not%20provided); __utma=71512449.1727452521.1662341097.1664379355.1664894719.7; __utmt=1; __utmb=71512449.2.10.1664894719; JSESSIONID=ABBDF073285A2C0A380C1440F65CDB4C' \
  -H 'Origin: http://1d3p.wp.codeforces.com' \
  -H 'Pragma: no-cache' \
  -H 'Referer: http://1d3p.wp.codeforces.com/' \
  -H 'Upgrade-Insecure-Requests: 1' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36' \
  --data-raw '_af=34be50b38beccce4&proof='$((num*num))'&amount='$num'&submit=Submit' \
  --compressed \
  --insecure

done